export const English = {
  home: {
    title: "Category",
    subheading: "Total Category",
  },
  selected_category: {
    order: "Place Order",
  },
  drawer: {
    home: "Home",
    language: "Language",
    application: "Are You A worker?",
    profile: "Profile",
    sign_out: "Sign out",
  },
  language: {
    title: "Language",
    subheading: "List of Languages",
  },
  application: {
    title: "Application",
    category: "Select a Category",
    upload_image: "Upload Image",
    upload_cnic_front: "Upload Cnic Front Side",
    upload_cnic_back: "Upload Cnic Back Side",
    cnic_number: "Cnic Number",
    parent_cinc: "Parent Cnic Number",
    address: "Address",
    submit_form: "Submit Form",
    city: "City",
    working_rate: "Working Rate Per Hour",
  },
  profile: {
    placed_task: "Placed Tasks",
    wallet: "Wallet",
    history: "History",
    reviews: "Reviews",
    online_training: "Online Training",
    notification: "Notifications",
    setting: "Setting",
    sign_out: "Sign out",
    assigned_task: "Assigned Tasks",
    promo: "Promo",
    favorites: "Favorites",
  },
  promo: {
    title: "Promo",
    expires: "Expire At:",
    status: "Status",
    used: "Used",
    not_used: "Not Used",
    expired: "Expired",
    not_expired: "Not Expired",
  },
  placedTask: {
    title: "Placed Task",
    my_task: "My Task",
    assigned_task: "Assigned Task",
    view_details: "View Details",
    accept: "Accept",
    reject: "Reject",
    cancel: "cancel",
    description: "Description",
    hours: "Hours",
  },
  task_details: {
    title: "Order Details",
    subheading: "Order",
    order_from: "Order From",
    order_to: "Order To",
    phone: "Phone",
    gender: "Gender",
    chat: "Chat",
    complain: "Complain",
    price: "Price",
    hours: "Hours",
    status: "Status",
    worker_status: "Worker Status",
    commission: "Commission",
    address: "Address",
    description: "Description",
    completed: "Completed",
  },
  complaint: {
    title: "Complaint Box",
    subheading: "Order",
    complaint_to: "Complaint To",
    phone: "Phone",
    gender: "Gender",
    submit: "Submit",
  },
  wallet: {
    title: "Wallet",
    current_wallet: "Current Wallet",
    add_wallet: "Add Wallet",
    pay: "Pay",
    pending_amount: "Pending Amount",
    amount: "Amount",
  },
  add_wallet: {
    title: "Add Wallet",
    amount: "Amount",
    add: "Add",
  },
  history: {
    title: "History",
    my_task: "My Task",
    assigned_task: "Assigned Task",
    view_details: "View Details",
    price: "Price",
    hours: "Hours",
  },
  reviews: {
    title: "Reviews",
  },
  online_training: {
    title: "Online Training",
  },
  notification: {
    title: "Notification",
  },
  setting: {
    title: "Setting",
    subheading: "Information",
    name: "Name",
    email: "Email",
    phone: "Phone",
    verify: "Verify",
    dob: "Date of Birth",
    update_profile: "Update Profile",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    change_password: "Change Password",
  },
  add_order: {
    title: "Add Order",
    subheading: "Order To",
    gender: "Gender",
    male: "Male",
    female: "Female",
    price: "Price",
    working_hour: "Worker Hour",
    address: "Address",
    place_order: "Place the Order",
    description: "Enter Task Description",
  },
};
